import { useState } from 'react';
import type { Transaction, DateRange } from '../types';
import { formatCurrency, formatDate } from '../utils/helpers';
import { Button, Dialog } from './ui';
import { Download, Copy, Check, MessageCircle } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { auth } from '../lib/firebase';

interface ExportShareProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  transactions: Transaction[];
  dateRange: DateRange;
  userCity?: string;
}

export const ExportShare = ({
  open,
  onOpenChange,
  transactions,
  dateRange,
  userCity = 'Sukabumi',
}: ExportShareProps) => {
  const [copied, setCopied] = useState(false);

  const fmtDateTime = (d: Date | string) => {
    const dt = typeof d === 'string' ? new Date(d) : d;
    return dt.toLocaleString('id-ID', {
      weekday: 'long', day: 'numeric', month: 'long', year: 'numeric',
      hour: '2-digit', minute: '2-digit',
    });
  };

  const fmtDate = (d: Date | string) => {
    const dt = typeof d === 'string' ? new Date(d) : d;
    return dt.toLocaleDateString('id-ID', {
      weekday: 'long', day: 'numeric', month: 'long', year: 'numeric',
    });
  };

  const handleCopyShare = () => {
    const sorted = [...transactions].sort(
      (a, b) => new Date(a.date).getTime() - new Date(b.date).getTime()
    );
    const txLines = sorted
      .map((t) => {
        const bullet = t.type === 'income' ? '[+]' : '[-]';
        const sign = t.type === 'income' ? '+' : '-';
        const desc = t.description ? ` - ${t.description}` : '';
        return `${bullet} ${t.category}${desc}: ${sign}${formatCurrency(t.amount)}`;
      })
      .join('\n');

    const message =
`Keuanganku - Ringkasan Keuangan
================================
Periode  : ${fmtDateTime(new Date())}

${txLines}

• Total Pemasukan  : ${formatCurrency(income)}
• Total Pengeluaran: ${formatCurrency(expense)}
• Saldo Akhir      : ${formatCurrency(balance)}
https://setoran.massbim.my.id`;

    navigator.clipboard.writeText(message);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const getDateRangeLabel = () => {
    const labels: Record<DateRange, string> = {
      today: 'Hari Ini',
      week: 'Minggu Ini',
      month: 'Bulan Ini',
      year: 'Tahun Ini',
      custom: 'Custom',
    };
    return labels[dateRange];
  };

  const calculateSummary = () => {
    const income = transactions
      .filter((t) => t.type === 'income')
      .reduce((sum, t) => sum + t.amount, 0);
    const expense = transactions
      .filter((t) => t.type === 'expense')
      .reduce((sum, t) => sum + t.amount, 0);
    const balance = income - expense;

    return { income, expense, balance };
  };

  const { income, expense, balance } = calculateSummary();

  const exportToPDF = () => {
    const doc = new jsPDF();
    const pageW = doc.internal.pageSize.width;
    const pageH = doc.internal.pageSize.height;
    const MARGIN_BOTTOM = 22;
    const FOOTER_Y = pageH - 8;

    // Footer gabungan: disclaimer + branding, dengan wrap
    const FOOTER_FULL =
      'Dokumen ini dihasilkan secara sistematis oleh platform Setoranku (https://setoran.massbim.my.id). ' +
      'Segala perubahan data setelah waktu pencetakan tidak tertera pada dokumen ini. — Kelola Keuangan dengan Cerdas.';

    // POST_TABLE_HEIGHT: entri(8)+gap(10)+summary(26)+gap(6)+garis(1)+gap(16)+signature(46) = ~113
    const POST_TABLE_HEIGHT = 113;

    const now = new Date();
    const nowDate = fmtDate(now);
    const nowTime = now.toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' });

    const drawFooter = (pageNum: number) => {
      doc.setFontSize(6.5);
      doc.setFont('helvetica', 'italic');
      doc.setTextColor(160, 160, 160);
      const footerLines = doc.splitTextToSize(FOOTER_FULL, pageW - 28);
      // Footer teks rata tengah, nomor halaman di kanan bawah
      const footerTextY = FOOTER_Y - (footerLines.length - 1) * 3.5;
      doc.text(footerLines, pageW / 2, footerTextY, { align: 'center' });
      doc.setFont('helvetica', 'normal');
      doc.text(`Halaman ${pageNum} dari {TOTAL}`, pageW - 14, FOOTER_Y, { align: 'right' });
    };

    // ── Header bar ──
    doc.setFillColor(59, 130, 246);
    doc.rect(0, 0, pageW, 24, 'F');
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(255, 255, 255);
    doc.text('KEUANGANKU — Laporan Keuangan', 14, 13);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.text('Generated by: massbim.my.id', 14, 20);

    // ── Meta — label di X=14, nilai di X=42 ──
    doc.setTextColor(60, 60, 60);
    doc.setFontSize(9);
    const labelX = 14;
    const colonX = 42;
    doc.text('Periode',    labelX, 32); doc.text(`: ${getDateRangeLabel()}`, colonX, 32);
    doc.text('Tanggal',    labelX, 38); doc.text(`: ${nowDate}`,             colonX, 38);
    doc.text('Pukul',      labelX, 44); doc.text(`: ${nowTime} WIB`,         colonX, 44);

    // ── Transaction table ──
    const sorted = [...transactions].sort(
      (a, b) => new Date(a.date).getTime() - new Date(b.date).getTime()
    );
    const tableData = sorted.map((t, i) => [
      String(i + 1),
      fmtDateTime(t.date),
      t.category,
      t.description?.trim() || '-',
      (t.type === 'income' ? '+' : '-') + formatCurrency(t.amount),
    ]);

    let pageCount = 1;
    autoTable(doc, {
      head: [['No.', 'Tanggal & Jam', 'Kategori', 'Deskripsi', 'Jumlah']],
      body: tableData,
      startY: 50,
      margin: { bottom: MARGIN_BOTTOM + 6 }, // ruang lebih untuk footer 2 baris
      styles: { fontSize: 8, cellPadding: 4 },
      headStyles: { fillColor: [59, 130, 246], textColor: 255, fontStyle: 'bold', halign: 'center' },
      alternateRowStyles: { fillColor: [248, 250, 252] },
      columnStyles: {
        0: { halign: 'center', cellWidth: 10 },
        1: { halign: 'center', cellWidth: 52 },
        2: { halign: 'left' },
        3: { halign: 'center' },
        4: { halign: 'right', cellWidth: 36 },
      },
      didDrawPage: (data) => {
        drawFooter(data.pageNumber);
        pageCount = data.pageNumber;
      },
    });

    // ── Post-table block (hanya halaman terakhir) ──
    let finalY = (doc as any).lastAutoTable.finalY + 10;

    if (finalY + POST_TABLE_HEIGHT > pageH - MARGIN_BOTTOM - 6) {
      doc.addPage();
      pageCount += 1;
      drawFooter(pageCount);
      finalY = 20;
    }

    // Statistik entri
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 100, 100);
    doc.text(`Total Entri: ${transactions.length} Transaksi`, 14, finalY);
    finalY += 10;

    // Summary box
    doc.setFillColor(241, 245, 249);
    doc.roundedRect(14, finalY, pageW - 28, 26, 3, 3, 'F');
    const colW = (pageW - 28) / 3;
    const positions = [
      { label: 'Total Pemasukan',   value: formatCurrency(income),  color: [22, 163, 74]  as [number,number,number], x: 20 },
      { label: 'Total Pengeluaran', value: formatCurrency(expense), color: [220, 38, 38]  as [number,number,number], x: 14 + colW + 6 },
      { label: 'Saldo Akhir',       value: formatCurrency(balance), color: (balance >= 0 ? [37, 99, 235] : [202, 138, 4]) as [number,number,number], x: 14 + colW * 2 + 6 },
    ];
    positions.forEach(({ label, value, color, x }) => {
      doc.setFontSize(7.5); doc.setFont('helvetica', 'bold');   doc.setTextColor(...color); doc.text(label, x, finalY + 9);
      doc.setFontSize(10);  doc.setFont('helvetica', 'normal'); doc.setTextColor(...color); doc.text(value, x, finalY + 20);
    });
    finalY += 32;

    // Garis pemisah
    doc.setDrawColor(200, 200, 200);
    doc.line(14, finalY, pageW - 14, finalY);
    finalY += 16; // jarak 40+ unit dari summary box ke tanda tangan

    // Signature area — tengah kolom kanan, hanya halaman terakhir
    const ownerName = auth.currentUser?.displayName || 'Pemilik Akun';
    const sigX = pageW / 2 + (pageW / 2 - 14) / 2;

    doc.setFontSize(9); doc.setFont('helvetica', 'normal'); doc.setTextColor(60, 60, 60);
    doc.text(`${userCity}, ${fmtDate(now)}`, sigX, finalY, { align: 'center' });
    finalY += 20;
    doc.text('( ________________________ )', sigX, finalY, { align: 'center' });
    finalY += 6;
    doc.setFontSize(8);
    doc.text(ownerName, sigX, finalY, { align: 'center' });

    // ── Patch nomor halaman total (two-pass) ──
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFillColor(255, 255, 255);
      doc.rect(pageW - 52, FOOTER_Y - 5, 52, 7, 'F');
      doc.setFontSize(6.5);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(160, 160, 160);
      doc.text(`Halaman ${i} dari ${pageCount}`, pageW - 14, FOOTER_Y, { align: 'right' });
    }

    doc.save(`keuanganku-${dateRange}-${now.toISOString().split('T')[0]}.pdf`);
    onOpenChange(false);
  };

  const exportToExcel = () => {
    const summaryData = [
      ['LAPORAN KEUANGAN PRIBADI'],
      ['Periode', getDateRangeLabel()],
      ['Tanggal Laporan', formatDate(new Date(), 'long')],
      [],
      ['RINGKASAN'],
      ['Pemasukan', income],
      ['Pengeluaran', expense],
      ['Saldo', balance],
      [],
      ['DETAIL TRANSAKSI'],
      ['Tanggal', 'Tipe', 'Kategori', 'Deskripsi', 'Jumlah'],
    ];
    
    const transactionData = transactions.map((t) => [
      formatDate(t.date, 'long'),
      t.type === 'income' ? 'Pemasukan' : 'Pengeluaran',
      t.category,
      t.description || '-',
      t.amount
    ]);
    
    const allData = [...summaryData, ...transactionData];
    
    const ws = XLSX.utils.aoa_to_sheet(allData);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, 'Laporan Keuangan');
    
    XLSX.writeFile(wb, `laporan-keuangan-${dateRange}-${new Date().toISOString().split('T')[0]}.xlsx`);
    onOpenChange(false);
  };

  const shareToWhatsApp = () => {
    const sorted = [...transactions].sort(
      (a, b) => new Date(a.date).getTime() - new Date(b.date).getTime()
    );
    const txLines = sorted
      .map((t) => {
        const bullet = t.type === 'income' ? '•(+)' : '•(-)';
        const sign = t.type === 'income' ? '+' : '-';
        const desc = t.description ? ` - ${t.description}` : '';
        return `${bullet} ${t.category}${desc}: ${sign}${formatCurrency(t.amount)}`;
      })
      .join('\n');

    const message =
`Halo! Berikut rincian keuangan saya:
${fmtDateTime(new Date())}

${txLines}

• Total Pemasukan  : ${formatCurrency(income)}
• Total Pengeluaran: ${formatCurrency(expense)}
• Saldo Akhir      : ${formatCurrency(balance)}
Kelola di: https://setoran.massbim.my.id`;

    window.open(`https://wa.me/?text=${encodeURIComponent(message)}`, '_blank');
  };

  return (
    <Dialog
      open={open}
      onOpenChange={onOpenChange}
      title="Bagikan & Export Laporan"
      className="max-w-lg"
    >
      <div className="space-y-6">
        {/* Summary Preview */}
        <div className="grid grid-cols-3 gap-3 p-4 bg-gradient-to-r from-slate-50 to-slate-100 rounded-lg">
          <div>
            <p className="text-xs text-slate-600">Pemasukan</p>
            <p className="text-lg font-bold text-green-600">{formatCurrency(income)}</p>
          </div>
          <div>
            <p className="text-xs text-slate-600">Pengeluaran</p>
            <p className="text-lg font-bold text-red-600">{formatCurrency(expense)}</p>
          </div>
          <div>
            <p className="text-xs text-slate-600">Saldo</p>
            <p className={`text-lg font-bold ${balance >= 0 ? 'text-blue-600' : 'text-yellow-600'}`}>
              {formatCurrency(balance)}
            </p>
          </div>
        </div>

        {/* Share Section */}
        <div className="space-y-3">
          <h3 className="font-semibold text-slate-900">Bagikan Ringkasan</h3>
          <div className="flex gap-2">
            <Button
              onClick={shareToWhatsApp}
              variant="success"
              className="flex-1 gap-2"
            >
              <MessageCircle size={16} /> WhatsApp
            </Button>
            <Button
              onClick={handleCopyShare}
              variant={copied ? 'success' : 'secondary'}
              className="flex-1 gap-2"
            >
              {copied ? (
                <>
                  <Check size={16} /> Tersalin!
                </>
              ) : (
                <>
                  <Copy size={16} /> Salin Teks
                </>
              )}
            </Button>
          </div>
        </div>

        {/* Export Section */}
        <div className="space-y-3 border-t pt-4">
          <h3 className="font-semibold text-slate-900">Export Laporan</h3>
          <div className="space-y-2">
            <Button
              fullWidth
              variant="secondary"
              onClick={exportToPDF}
              className="justify-center gap-2"
            >
              <Download size={16} /> Export ke PDF
            </Button>
            <Button
              fullWidth
              variant="secondary"
              onClick={exportToExcel}
              className="justify-center gap-2"
            >
              <Download size={16} /> Export ke Excel
            </Button>
          </div>
        </div>

        {/* Alert */}
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-3">
          <p className="text-xs text-blue-700">
            💡 Bagikan ringkasan keuangan Anda melalui WhatsApp atau export laporan ke PDF/Excel untuk keperluan administrasi.
          </p>
        </div>
      </div>
    </Dialog>
  );
};
